# Generated by Django 5.2.5 on 2025-08-18 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма чека', max_digits=10, null=True)),
                ('note', models.CharField(blank=True, help_text='Комментарий кассира', max_length=255)),
                ('pos_ref', models.CharField(blank=True, help_text='Номер чека/операции', max_length=64)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='coupons.coupon')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['redeemed_at'], name='redemptions_redeeme_9b4e95_idx')],
            },
        ),
    ]
