# Generated by Django 5.2.5 on 2025-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
