# Generated by Django 5.2.5 on 2025-08-18 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('campaigns', '0006_alter_trackevent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IGAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_user_id', models.CharField(max_length=50, unique=True)),
                ('page_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('access_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('permissions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Error')], default='connected', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_errors', models.JSONField(default=list)),
                ('auto_publish_enabled', models.BooleanField(default=True)),
                ('dm_bot_enabled', models.BooleanField(default=True)),
                ('comment_moderation_enabled', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig_account', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
            },
        ),
        migrations.CreateModel(
            name='IGDMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_keywords', models.JSONField(default=list)),
                ('trigger_type', models.CharField(choices=[('contains', 'Contains keyword'), ('equals', 'Exact match'), ('starts_with', 'Starts with'), ('regex', 'Regular expression')], default='contains', max_length=20)),
                ('response_text', models.TextField()),
                ('include_coupon', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_templates', to='integrations_ig.igaccount')),
                ('coupon_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_dm_templates', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Instagram DM Template',
                'verbose_name_plural': 'Instagram DM Templates',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IGMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_media_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('creation_id', models.CharField(blank=True, max_length=50)),
                ('permalink', models.URLField(blank=True)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('reel', 'Reel'), ('carousel', 'Carousel Album')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('media_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('children_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('utm_source', models.CharField(default='ig', max_length=50)),
                ('utm_medium', models.CharField(default='social', max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_insights_sync', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='integrations_ig.igaccount')),
            ],
            options={
                'verbose_name': 'Instagram Media',
                'verbose_name_plural': 'Instagram Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IGComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_comment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ig_parent_id', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('author_username', models.CharField(max_length=100)),
                ('author_id', models.CharField(blank=True, max_length=50)),
                ('hidden', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_action', models.CharField(blank=True, max_length=20)),
                ('ai_sentiment', models.SmallIntegerField(blank=True, null=True)),
                ('ai_toxic', models.BooleanField(default=False)),
                ('ai_labels', models.JSONField(default=list)),
                ('ai_summary', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ig_comments', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='integrations_ig.igmedia')),
            ],
            options={
                'verbose_name': 'Instagram Comment',
                'verbose_name_plural': 'Instagram Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IGThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('recipient_id', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_bot_response', models.BooleanField(default=False)),
                ('is_within_24h_window', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_messages', to='integrations_ig.igaccount')),
            ],
            options={
                'verbose_name': 'Instagram DM',
                'verbose_name_plural': 'Instagram DMs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IGWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('message', 'Message'), ('mention', 'Mention'), ('media_status', 'Media Status Change'), ('account_update', 'Account Update')], max_length=20)),
                ('raw_payload', models.JSONField()),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations_ig.igaccount')),
            ],
            options={
                'verbose_name': 'Instagram Webhook Event',
                'verbose_name_plural': 'Instagram Webhook Events',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='igaccount',
            index=models.Index(fields=['ig_user_id'], name='integration_ig_user_cb780c_idx'),
        ),
        migrations.AddIndex(
            model_name='igaccount',
            index=models.Index(fields=['business', 'status'], name='integration_busines_70c3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='igdmtemplate',
            index=models.Index(fields=['account', 'enabled'], name='integration_account_2e78ab_idx'),
        ),
        migrations.AddIndex(
            model_name='igdmtemplate',
            index=models.Index(fields=['priority'], name='integration_priorit_56d43b_idx'),
        ),
        migrations.AddIndex(
            model_name='igmedia',
            index=models.Index(fields=['account', 'status'], name='integration_account_04915e_idx'),
        ),
        migrations.AddIndex(
            model_name='igmedia',
            index=models.Index(fields=['ig_media_id'], name='integration_ig_medi_e05cba_idx'),
        ),
        migrations.AddIndex(
            model_name='igmedia',
            index=models.Index(fields=['publish_at'], name='integration_publish_504254_idx'),
        ),
        migrations.AddIndex(
            model_name='igmedia',
            index=models.Index(fields=['utm_campaign'], name='integration_utm_cam_22e41f_idx'),
        ),
        migrations.AddIndex(
            model_name='igcomment',
            index=models.Index(fields=['media', 'created_at'], name='integration_media_i_eb060d_idx'),
        ),
        migrations.AddIndex(
            model_name='igcomment',
            index=models.Index(fields=['ig_comment_id'], name='integration_ig_comm_e10b25_idx'),
        ),
        migrations.AddIndex(
            model_name='igcomment',
            index=models.Index(fields=['author_username'], name='integration_author__1c1cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='igcomment',
            index=models.Index(fields=['ai_toxic', 'hidden'], name='integration_ai_toxi_d7b51f_idx'),
        ),
        migrations.AddIndex(
            model_name='igthreadmessage',
            index=models.Index(fields=['account', 'thread_id', 'timestamp'], name='integration_account_c100d3_idx'),
        ),
        migrations.AddIndex(
            model_name='igthreadmessage',
            index=models.Index(fields=['message_id'], name='integration_message_c1b784_idx'),
        ),
        migrations.AddIndex(
            model_name='igthreadmessage',
            index=models.Index(fields=['direction', 'is_read'], name='integration_directi_97e64a_idx'),
        ),
        migrations.AddIndex(
            model_name='igwebhookevent',
            index=models.Index(fields=['kind', 'processed'], name='integration_kind_c514a4_idx'),
        ),
        migrations.AddIndex(
            model_name='igwebhookevent',
            index=models.Index(fields=['account', 'delivered_at'], name='integration_account_a4ef8d_idx'),
        ),
        migrations.AddIndex(
            model_name='igwebhookevent',
            index=models.Index(fields=['object_id'], name='integration_object__b052a1_idx'),
        ),
    ]
