# Generated by Django 5.2.5 on 2025-08-18 18:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(help_text='Нормализованный номер телефона', max_length=32)),
                ('first_seen', models.DateTimeField(blank=True, help_text='Первое взаимодействие', null=True)),
                ('last_issue_at', models.DateTimeField(blank=True, help_text='Последняя выдача купона', null=True)),
                ('last_redeem_at', models.DateTimeField(blank=True, help_text='Последнее погашение', null=True)),
                ('issues_count', models.PositiveIntegerField(default=0, help_text='Количество выданных купонов')),
                ('redeems_count', models.PositiveIntegerField(default=0, help_text='Количество погашений')),
                ('redeem_amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая сумма погашений', max_digits=12)),
                ('recency_days', models.PositiveIntegerField(default=9999, help_text='Дни с последнего погашения')),
                ('r_score', models.PositiveSmallIntegerField(default=1, help_text='Recency score (1-5)')),
                ('f_score', models.PositiveSmallIntegerField(default=1, help_text='Frequency score (1-5)')),
                ('m_score', models.PositiveSmallIntegerField(default=1, help_text='Monetary score (1-5)')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Теги клиента: ['coffee', 'lunch']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_customers', to='businesses.business')),
            ],
            options={
                'ordering': ['-last_redeem_at', '-redeems_count'],
                'indexes': [models.Index(fields=['business', 'phone_e164'], name='customers_c_busines_51b82d_idx'), models.Index(fields=['business', 'recency_days'], name='customers_c_busines_1020a5_idx'), models.Index(fields=['business', 'redeems_count'], name='customers_c_busines_d0cb8b_idx'), models.Index(fields=['business', 'r_score', 'f_score', 'm_score'], name='customers_c_busines_77693b_idx')],
                'unique_together': {('business', 'phone_e164')},
            },
        ),
    ]
