# Generated by Django 5.2.5 on 2025-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_redeem_date',
            field=models.DateField(blank=True, help_text='Дата последнего погашения', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='streak_best',
            field=models.IntegerField(default=0, help_text='Лучшая серия посещений'),
        ),
        migrations.AddField(
            model_name='customer',
            name='streak_count',
            field=models.IntegerField(default=0, help_text='Текущая серия посещений'),
        ),
    ]
