# Generated by Django 5.2.5 on 2025-08-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сегмента', max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly имя', max_length=140)),
                ('kind', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='custom', help_text='Тип сегмента: системный или пользовательский', max_length=12)),
                ('definition', models.JSONField(blank=True, default=dict, help_text='JSON правила фильтрации')),
                ('is_dynamic', models.BooleanField(default=True, help_text='Динамический сегмент пересчитывается автоматически')),
                ('size_cached', models.PositiveIntegerField(default=0, help_text='Кэшированный размер сегмента')),
                ('preview', models.JSONField(blank=True, default=list, help_text='Превью участников (маскированные телефоны)')),
                ('last_built_at', models.DateTimeField(blank=True, help_text='Время последнего перестроения', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Сегмент активен')),
                ('description', models.TextField(blank=True, help_text='Описание сегмента')),
                ('color', models.CharField(default='#3B82F6', help_text='Цвет сегмента в HEX', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='businesses.business')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='customers.customer')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='segments.segment')),
            ],
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['business', 'enabled'], name='segments_se_busines_5a7740_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['business', 'kind'], name='segments_se_busines_1ec149_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['business', 'last_built_at'], name='segments_se_busines_07bfe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('business', 'slug')},
        ),
        migrations.AddIndex(
            model_name='segmentmember',
            index=models.Index(fields=['segment', 'customer'], name='segments_se_segment_685a19_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentmember',
            index=models.Index(fields=['customer', 'added_at'], name='segments_se_custome_11aafa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentmember',
            unique_together={('segment', 'customer')},
        ),
    ]
