# Generated by Django 5.2.5 on 2025-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='issue_limit',
            field=models.PositiveIntegerField(default=100, help_text='Сколько купонов можно выдать'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='per_phone_limit',
            field=models.PositiveIntegerField(default=1, help_text='Сколько купонов на 1 номер'),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='type',
            field=models.CharField(choices=[('landing_view', 'Landing View'), ('landing_click', 'Landing Click'), ('coupon_issue', 'Coupon Issue')], max_length=32),
        ),
    ]
