# Generated by Django 5.2.5 on 2025-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_issue_limit_campaign_per_phone_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackevent',
            name='type',
            field=models.CharField(choices=[('landing_view', 'Landing View'), ('landing_click', 'Landing Click'), ('coupon_issue', 'Coupon Issue'), ('coupon_redeem', 'Coupon Redeem')], max_length=32),
        ),
    ]
