# Generated by Django 5.2.5 on 2025-08-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_trackevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign'),
        ),
    ]
