# Generated by Django 5.2.5 on 2025-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_trackevent_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackevent',
            name='type',
            field=models.CharField(choices=[('landing_view', 'Landing View'), ('landing_click', 'Landing Click'), ('coupon_issue', 'Coupon Issue'), ('coupon_redeem', 'Coupon Redeem'), ('referral_click', 'Referral Click'), ('review_submit', 'Review Submit')], max_length=32),
        ),
    ]
