# Generated by Django 5.2.5 on 2025-08-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Issue'), ('redeem', 'Redeem')], max_length=12)),
                ('campaign_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.TextField(blank=True)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('warn', 'Warn'), ('block', 'Block')], default='allow', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='businesses.business')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='coupons.coupon')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='fraud_riske_busines_03f8f2_idx'), models.Index(fields=['phone'], name='fraud_riske_phone_89536f_idx'), models.Index(fields=['ip'], name='fraud_riske_ip_413fa9_idx'), models.Index(fields=['kind'], name='fraud_riske_kind_d8b021_idx')],
            },
        ),
    ]
