# Generated by Django 5.2.5 on 2025-08-19 05:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('customers', '0001_initial'),
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('manual', 'Ручной запуск'), ('scheduled', 'По расписанию'), ('event_coupon_issued', 'Выдан купон'), ('event_coupon_redeemed', 'Погашен купон'), ('event_review_toxic', 'Токсичный отзыв'), ('event_segment_enter', 'Вход в сегмент'), ('expiry_24h', 'Истекает через 24ч'), ('expiry_1h', 'Истекает через 1ч')], default='manual', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('running', 'Выполняется'), ('completed', 'Завершена'), ('paused', 'Приостановлена'), ('cancelled', 'Отменена')], default='draft', max_length=12)),
                ('custom_filter', models.JSONField(blank=True, default=dict)),
                ('strategy', models.JSONField(blank=True, default=dict)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('budget_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blasts', to='businesses.business')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='segments.segment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_points', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Неудачно'), ('skipped', 'Пропущен')], default='pending', max_length=12)),
                ('current_step', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='blasts.blast')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_recipients', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram DM'), ('wallet', 'Wallet Push')], max_length=12)),
                ('value', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('opt_in', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('cost_weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MessagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channels', models.JSONField(default=list)),
                ('quiet_hours_start', models.TimeField(default='21:00')),
                ('quiet_hours_end', models.TimeField(default='09:00')),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=50)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('max_messages_per_day', models.IntegerField(default=3)),
                ('max_messages_per_week', models.IntegerField(default=10)),
                ('allow_promotional', models.BooleanField(default=True)),
                ('allow_transactional', models.BooleanField(default=True)),
                ('allow_expiry_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_preferences', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_preferences', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram DM'), ('wallet', 'Wallet Push')], max_length=12)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('a_b_bucket', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram DM'), ('wallet', 'Wallet Push')], max_length=12)),
                ('provider', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('opened', 'Открыто'), ('clicked', 'Клик'), ('failed', 'Неудачно'), ('bounced', 'Отклонено'), ('unsubscribed', 'Отписка')], default='queued', max_length=15)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blast_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='blasts.blastrecipient')),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='blasts.contactpoint')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blasts.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('original_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('utm_source', models.CharField(blank=True, max_length=50)),
                ('utm_medium', models.CharField(blank=True, max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('clicks_count', models.IntegerField(default=0)),
                ('unique_clicks_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='blasts.blast')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='businesses.business')),
                ('delivery_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blasts.deliveryattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ShortLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('fingerprint', models.CharField(blank=True, max_length=32)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='blasts.shortlink')),
            ],
        ),
        migrations.AddIndex(
            model_name='blast',
            index=models.Index(fields=['business', 'status'], name='blasts_blas_busines_75cc65_idx'),
        ),
        migrations.AddIndex(
            model_name='blast',
            index=models.Index(fields=['trigger', 'status'], name='blasts_blas_trigger_485199_idx'),
        ),
        migrations.AddIndex(
            model_name='blast',
            index=models.Index(fields=['schedule_at'], name='blasts_blas_schedul_88b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='blastrecipient',
            index=models.Index(fields=['blast', 'status'], name='blasts_blas_blast_i_db476b_idx'),
        ),
        migrations.AddIndex(
            model_name='blastrecipient',
            index=models.Index(fields=['status', 'next_attempt_at'], name='blasts_blas_status_0040eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blastrecipient',
            unique_together={('blast', 'customer')},
        ),
        migrations.AddIndex(
            model_name='contactpoint',
            index=models.Index(fields=['business', 'type'], name='blasts_cont_busines_8ad7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpoint',
            index=models.Index(fields=['customer', 'type'], name='blasts_cont_custome_ff6d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpoint',
            index=models.Index(fields=['type', 'verified', 'opt_in'], name='blasts_cont_type_22e85c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactpoint',
            unique_together={('business', 'type', 'value')},
        ),
        migrations.AddIndex(
            model_name='messagepreference',
            index=models.Index(fields=['business', 'customer'], name='blasts_mess_busines_e7f17b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagepreference',
            unique_together={('business', 'customer')},
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['business', 'channel', 'locale'], name='blasts_mess_busines_657723_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['channel', 'is_active'], name='blasts_mess_channel_0e1055_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['blast_recipient', 'status'], name='blasts_deli_blast_r_390e63_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['channel', 'status'], name='blasts_deli_channel_f33b01_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['external_id'], name='blasts_deli_externa_c12a23_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['sent_at'], name='blasts_deli_sent_at_b6a7be_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlink',
            index=models.Index(fields=['business', 'blast'], name='blasts_shor_busines_8ed1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlink',
            index=models.Index(fields=['short_code'], name='blasts_shor_short_c_b41fda_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlinkclick',
            index=models.Index(fields=['short_link', 'clicked_at'], name='blasts_shor_short_l_24133c_idx'),
        ),
        migrations.AddIndex(
            model_name='shortlinkclick',
            index=models.Index(fields=['fingerprint'], name='blasts_shor_fingerp_9458bc_idx'),
        ),
    ]
