# Generated by Django 5.2.5 on 2025-08-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_issue_limit_campaign_per_phone_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['campaign', 'issued_at'], name='coupons_cou_campaig_3e3c0c_idx')],
            },
        ),
    ]
