# Generated by Django 5.2.5 on 2025-08-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('campaigns', '0006_alter_trackevent_type'),
        ('coupons', '0002_coupon_metadata_coupon_risk_flag_coupon_risk_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google', 'Google Wallet'), ('apple', 'Apple Wallet')], max_length=10)),
                ('class_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('background_color', models.CharField(default='#111827', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(default='UNDER_REVIEW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_classes', to='businesses.business')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'is_active'], name='wallet_wall_platfor_e016d0_idx')],
                'unique_together': {('business', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='WalletPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=32)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('platform', models.CharField(choices=[('google', 'Google Wallet'), ('apple', 'Apple Wallet')], max_length=10)),
                ('class_id', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(default='Скидочная карта', max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('barcode_value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='created', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('notification_sent_24h', models.BooleanField(default=False)),
                ('notification_sent_1h', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_passes', to='businesses.business')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_passes', to='campaigns.campaign')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_passes', to='coupons.coupon')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='wallet_wall_busines_9e295f_idx'), models.Index(fields=['customer_phone'], name='wallet_wall_custome_6b79e9_idx'), models.Index(fields=['platform', 'status'], name='wallet_wall_platfor_35b0da_idx'), models.Index(fields=['valid_until'], name='wallet_wall_valid_u_03ff48_idx')],
            },
        ),
    ]
