# Generated by Django 5.2.5 on 2025-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpass',
            name='streak_data',
            field=models.JSONField(blank=True, default=dict, help_text='Данные серий посещений'),
        ),
    ]
