# Generated by Django 5.2.5 on 2025-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_labels',
            field=models.JSONField(blank=True, default=list, help_text='Темы отзыва: сервис, вкус, цена и т.д.'),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_sentiment',
            field=models.SmallIntegerField(blank=True, help_text='Тональность от -100 до +100', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='Краткое резюме отзыва', max_length=280),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_toxic',
            field=models.BooleanField(default=False, help_text='Содержит токсичный/неприемлемый контент'),
        ),
    ]
