# Generated by Django 5.2.5 on 2025-08-19 06:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_settings'),
        ('campaigns', '0006_alter_trackevent_type'),
        ('coupons', '0002_coupon_metadata_coupon_risk_flag_coupon_risk_score'),
        ('customers', '0002_customer_last_redeem_date_customer_streak_best_and_more'),
        ('segments', '0001_initial'),
        ('wallet', '0002_walletpass_streak_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryDropTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.IntegerField(help_text='Процент скидки (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('probability', models.DecimalField(decimal_places=2, help_text='Вероятность выпадения в процентах (0.01-100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('emoji', models.CharField(default='🎁', help_text='Эмодзи для отображения', max_length=10)),
                ('color', models.CharField(default='#FFD700', help_text='Цвет в HEX формате', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'discount_percent'],
            },
        ),
        migrations.CreateModel(
            name='MysteryDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='🎰 Потряси и получи скидку!', max_length=200)),
                ('subtitle', models.CharField(default='Встряхни телефон или поскреби экран', max_length=300)),
                ('daily_cap_per_phone', models.IntegerField(default=1, help_text='Максимум попыток на один телефон в день', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('daily_cap_total', models.IntegerField(default=1000, help_text='Максимум выдач в день по всей кампании', validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('scratch_enabled', models.BooleanField(default=True, help_text='Включить скретч-интерфейс')),
                ('shake_enabled', models.BooleanField(default=True, help_text='Включить shake-to-reveal')),
                ('background_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('auto_wallet_creation', models.BooleanField(default=True, help_text='Автоматически создавать Wallet карты')),
                ('send_notification', models.BooleanField(default=True, help_text='Отправлять уведомление о выигрыше')),
                ('enabled', models.BooleanField(default=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_redeems', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_drops', to='businesses.business')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_drops', to='campaigns.campaign')),
                ('tiers', models.ManyToManyField(related_name='mystery_drops', to='growth.mysterydroptier')),
            ],
        ),
        migrations.CreateModel(
            name='PowerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='⚡ Power Hour!', max_length=200)),
                ('discount_text', models.CharField(default='Скидка 30% следующий час!', max_length=100)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Длительность в минутах (15-180)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('auto_wallet_update', models.BooleanField(default=True, help_text='Обновлять Wallet карты')),
                ('wallet_background_color', models.CharField(default='#FF4444', max_length=7)),
                ('wallet_text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('send_blast', models.BooleanField(default=True, help_text='Отправить каскадную рассылку')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('running', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=10)),
                ('blast_sent', models.IntegerField(default=0)),
                ('wallet_updated', models.IntegerField(default=0)),
                ('coupons_issued', models.IntegerField(default=0)),
                ('coupons_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blast_segment', models.ForeignKey(blank=True, help_text='Сегмент для рассылки (если пустой - всем)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='segments.segment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_hours', to='businesses.business')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_hours', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MysteryDropAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('won', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_attempts', to='coupons.coupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_attempts', to='customers.customer')),
                ('mystery_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='growth.mysterydrop')),
                ('wallet_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mystery_attempts', to='wallet.walletpass')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='growth.mysterydroptier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mystery_drop', 'phone', 'created_at'], name='growth_myst_mystery_ff7558_idx'), models.Index(fields=['mystery_drop', 'created_at'], name='growth_myst_mystery_07b2eb_idx'), models.Index(fields=['phone', 'created_at'], name='growth_myst_phone_393744_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mysterydrop',
            index=models.Index(fields=['business', 'enabled'], name='growth_myst_busines_8c1e29_idx'),
        ),
        migrations.AddIndex(
            model_name='mysterydrop',
            index=models.Index(fields=['starts_at', 'ends_at'], name='growth_myst_starts__ac16be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mysterydrop',
            unique_together={('business', 'campaign')},
        ),
        migrations.AddIndex(
            model_name='powerhour',
            index=models.Index(fields=['business', 'status'], name='growth_powe_busines_1f3e46_idx'),
        ),
        migrations.AddIndex(
            model_name='powerhour',
            index=models.Index(fields=['starts_at', 'ends_at'], name='growth_powe_starts__a00c4f_idx'),
        ),
    ]
